-- Create the coupons table
CREATE TABLE coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  discount_percentage NUMERIC(5,2) NOT NULL,
  valid_from TIMESTAMP WITH TIME ZONE NOT NULL,
  valid_until TIMESTAMP WITH TIME ZONE NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Add RLS policies for the coupons table
ALTER TABLE coupons ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Coupons are viewable by everyone" ON coupons FOR SELECT USING (true);

-- Function to check if a coupon is valid
CREATE OR REPLACE FUNCTION is_coupon_valid(coupon_code TEXT)
RETURNS BOOLEAN AS $$
DECLARE
  valid BOOLEAN;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM coupons
    WHERE code = coupon_code
      AND is_active = TRUE
      AND valid_from <= CURRENT_TIMESTAMP
      AND valid_until >= CURRENT_TIMESTAMP
  ) INTO valid;
  RETURN valid;
END;
$$ LANGUAGE plpgsql;

-- Function to get coupon discount percentage
CREATE OR REPLACE FUNCTION get_coupon_discount(coupon_code TEXT)
RETURNS NUMERIC AS $$
DECLARE
  discount NUMERIC;
BEGIN
  SELECT discount_percentage INTO discount
  FROM coupons
  WHERE code = coupon_code
    AND is_active = TRUE
    AND valid_from <= CURRENT_TIMESTAMP
    AND valid_until >= CURRENT_TIMESTAMP;
  RETURN COALESCE(discount, 0);
END;
$$ LANGUAGE plpgsql;

